// <auto-generated />
namespace WebAppPassionProjectMVP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TablesPatientDoctorMedicalProcedure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TablesPatientDoctorMedicalProcedure));
        
        string IMigrationMetadata.Id
        {
            get { return "202402050114262_Tables-Patient-Doctor-MedicalProcedure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
